//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smloginregistration.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class user
    {
        public int UserId { get; set; }

        [Display(Name ="Full Name")]
        [Required(ErrorMessage ="Enter Full Name" , AllowEmptyStrings =true)]
        public string Fullname { get; set; }

        [Display(Name ="UserName")]
        [Required(ErrorMessage ="Enter Username")]
        public string Username { get; set; }

        
        [Required(ErrorMessage ="Enter Password")]
        [DataType(DataType.Password)]
        public string Password { get; set; }


        [Display(Name ="Comfirm Password")]
        [Compare("Password",ErrorMessage ="password doesn't match")]
        [Required(ErrorMessage ="Enter Comfirm password")]
        public string ComfirmPassword { get; set; }


        [Display(Name ="Email Address")]
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage ="Enter Email")]
        public string Email { get; set; }


    }
}
